(()=>{
const $=id=>document.getElementById(id),N=32,cell=10,colors=[null,'#222','#e53935','#1e88e5','#43a047','#fdd835'],names=['消しゴム','黒','赤','青','緑','黄色'];
let grid=Array.from({length:N},()=>Array(N).fill(0)),x=15,y=15,color=1,pen=false,history=[],audio=null,recognition=null,listening=false,sensorEnabled=false,lastShake=0;
const SHAKE_THRESHOLD=11,SHAKE_COOLDOWN=1000;
const canvas=$('canvas'),ctx=canvas.getContext('2d'),SR=window.SpeechRecognition||window.webkitSpeechRecognition;
$('capabilities').textContent=`音声認識 ${SR?'対応':'未対応'} · 振動 ${'vibrate'in navigator?'対応':'未対応'}`;
function save(){history.push({grid:grid.map(r=>r.slice()),x,y,color,pen});if(history.length>30)history.shift()}
function speak(message,always=false){$('said').textContent=message;if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(message);u.lang='ja-JP';speechSynthesis.speak(u)}}
function draw(){ctx.fillStyle='#fff';ctx.fillRect(0,0,320,320);for(let j=0;j<N;j++)for(let i=0;i<N;i++)if(grid[j][i]){ctx.fillStyle=colors[grid[j][i]];ctx.fillRect(i*cell,j*cell,cell,cell)}ctx.strokeStyle='#ddd';ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<=N;i++){ctx.moveTo(i*cell+.5,0);ctx.lineTo(i*cell+.5,320);ctx.moveTo(0,i*cell+.5);ctx.lineTo(320,i*cell+.5)}ctx.stroke();ctx.strokeStyle='#e85d04';ctx.lineWidth=2;ctx.strokeRect(x*cell+1,y*cell+1,8,8);if(pen){ctx.fillStyle='#e85d04';ctx.fillRect(x*cell+3,y*cell+3,4,4)}$('stat').textContent=`横${x+1} 縦${y+1} · ${pen?'ペン下':'ペン上'} · ${names[color]}`;$('pen').setAttribute('aria-pressed',String(pen));$('pen').setAttribute('aria-label',pen?'ペンを上げる':'ペンを下ろす');$('pen').title=pen?'ペンを上げる':'ペンを下ろす';document.querySelectorAll('.swatch').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===color)))}
function undo(){if(!history.length){speak('戻せる操作はありません');return}({grid,x,y,color,pen}=history.pop());draw();speak('元に戻しました')}
function describe(){let count=Array(6).fill(0),left=32,right=-1,top=32,bottom=-1;grid.forEach((r,j)=>r.forEach((v,i)=>{if(v){count[v]++;left=Math.min(left,i);right=Math.max(right,i);top=Math.min(top,j);bottom=Math.max(bottom,j)}}));const total=count.reduce((a,b)=>a+b,0);if(!total)return `まだ何も描かれていません。カーソルは横${x+1}、縦${y+1}です。`;const parts=count.map((n,i)=>n?`${names[i]}が${n}マス`:null).filter(Boolean).join('、');return `${parts}が描かれています。合計${total}マスです。範囲は横${left+1}から${right+1}、縦${top+1}から${bottom+1}です。`}
function effect(pattern=[70,45,70]){if(navigator.vibrate)navigator.vibrate(pattern);try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=660;g.gain.value=.12;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function micBeep(frequency,duration){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=frequency;g.gain.value=.1;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function traceFeedback(wasDrawn){if(pen)effect([24,20,24]);else if(wasDrawn){effect([12]);speak(`${names[grid[y][x]]}色`)} }
function command(input){const t=input.replace(/\s/g,'');if(!t)return;$('heard').textContent=`認識: ${input}`;if(/元に戻す|取り消し|undo/i.test(t)){undo();return}if(/状態|描かれ|説明/.test(t)){speak(describe(),true);return}if(/全部消|全消去|クリア/.test(t)){save();grid=Array.from({length:N},()=>Array(N).fill(0));draw();speak('全部消しました');return}if(/ペン.*(上げ|あげ)/.test(t)){save();pen=false;draw();speak('ペンを上げました');return}if(/ペン.*(下ろ|おろ)/.test(t)){save();pen=true;grid[y][x]=color;draw();speak('ペンを下ろしました');return}for(const [re,k]of [[/消しゴム/,0],[/黒/,1],[/赤/,2],[/青/,3],[/緑/,4],[/黄色|黄/,5]])if(re.test(t)){save();color=k;draw();speak(`${names[k]}を選びました`);return}const dict={'一':1,'二':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9,'十':10},n=Number((t.match(/\d+/)||[])[0])||dict[(t.match(/[一二三四五六七八九十]/)||[])[0]]||1;let dx=0,dy=0;if(/右/.test(t))dx=1;else if(/左/.test(t))dx=-1;else if(/上|うえ/.test(t))dy=-1;else if(/下|した/.test(t))dy=1;else if(/中央|真ん中/.test(t)){save();x=15;y=15;draw();speak('中央に移動しました');return}else if(/塗|点を打/.test(t)){save();grid[y][x]=color;draw();effect();return}else{speak('コマンドを認識できませんでした');return}save();x=Math.max(0,Math.min(31,x+dx*n));y=Math.max(0,Math.min(31,y+dy*n));if(pen)grid[y][x]=color;draw();effect();speak(`横${x+1}、縦${y+1}に移動しました`)}
colors.forEach((v,i)=>{const b=document.createElement('button');b.className='swatch';b.style.background=v||'#fff';b.textContent=v?'': '消';b.title=names[i];b.setAttribute('aria-label',names[i]);b.setAttribute('aria-pressed',String(i===color));b.addEventListener('click',()=>{save();color=i;draw();speak(`${names[i]}を選びました`)});$('palette').append(b)});
$('pen').addEventListener('click',()=>{save();pen=!pen;if(pen)grid[y][x]=color;draw();speak(pen?'ペンを下ろしました':'ペンを上げました')});$('undo').addEventListener('click',undo);$('describe').addEventListener('click',()=>speak(describe(),true));$('clear').addEventListener('click',()=>command('全部消す'));
$('commandForm').addEventListener('submit',e=>{e.preventDefault();command($('command').value);$('command').value='' });
function startListening(){if(listening){recognition.stop();return}if(!SR){speak('このブラウザーは音声認識に対応していません');return}recognition=new SR();recognition.lang='ja-JP';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)command(text);else $('heard').textContent=`聞き取り中: ${text}`}};recognition.onerror=e=>$('heard').textContent=`音声認識エラー: ${e.error}`;recognition.onend=()=>{const wasListening=listening;listening=false;$('listen').classList.remove('on');$('listen').textContent='🎙 マイク開始';$('listen').setAttribute('aria-pressed','false');if(wasListening)micBeep(520,.12)};try{recognition.start();listening=true;$('listen').classList.add('on');$('listen').textContent='■ マイク停止';$('listen').setAttribute('aria-pressed','true');micBeep(880,.08)}catch{$('heard').textContent='マイクを開始できません。接続とブラウザーの許可を確認してください。'}}
$('listen').addEventListener('click',startListening);
let gravity={x:0,y:0,z:0},hasGravity=false;
function motion(e){const a=e.acceleration;if(a&&[a.x,a.y,a.z].every(Number.isFinite)){triggerShake(a);return}const g=e.accelerationIncludingGravity;if(!g||![g.x,g.y,g.z].every(Number.isFinite))return;if(!hasGravity){gravity={x:g.x,y:g.y,z:g.z};hasGravity=true;return}const delta={x:g.x-gravity.x,y:g.y-gravity.y,z:g.z-gravity.z};gravity={x:gravity.x*.8+g.x*.2,y:gravity.y*.8+g.y*.2,z:gravity.z*.8+g.z*.2};triggerShake(delta)}
function triggerShake(delta={x:0,y:0,z:0}){const horizontal=Math.abs(delta.x)>=Math.abs(delta.y);const strength=horizontal?Math.abs(delta.x):Math.abs(delta.y);if(strength<SHAKE_THRESHOLD||Date.now()-lastShake<SHAKE_COOLDOWN)return;lastShake=Date.now();if(horizontal){$('sensorStatus').textContent='横振りを検出しました。元に戻します。';undo()}else{$('sensorStatus').textContent='縦振りを検出しました。マイクを開始します。';if(!listening)$('listen').click()}effect([35])}
async function enableShakeSensor(){const D=window.DeviceMotionEvent;if(!D){$('sensorStatus').textContent='この端末は加速度センサーに対応していません';return}try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')await audio.resume()}catch{}if(typeof D.requestPermission==='function'){try{if(await D.requestPermission()!=='granted')throw Error()}catch{$('sensorStatus').textContent='センサーの許可が必要です';return}}addEventListener('devicemotion',motion,{passive:true});sensorEnabled=true;$('sensorStatus').textContent='センサー待機中です。端末を振ってください'}
function cellAt(e){const r=canvas.getBoundingClientRect();return[Math.max(0,Math.min(31,Math.floor((e.clientX-r.left)/r.width*32))),Math.max(0,Math.min(31,Math.floor((e.clientY-r.top)/r.height*32)))]}canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);save();[x,y]=cellAt(e);const wasDrawn=Boolean(grid[y][x]);if(pen)grid[y][x]=color;traceFeedback(wasDrawn);draw()});canvas.addEventListener('pointermove',e=>{if(!e.buttons)return;const[a,b]=cellAt(e);if(a===x&&b===y)return;x=a;y=b;const wasDrawn=Boolean(grid[y][x]);if(pen)grid[y][x]=color;traceFeedback(wasDrawn);draw()});draw();
enableShakeSensor();draw();
})();